name: "18n coverage"
description: "Check i18n coverage of the project"
inputs:
  translations-path:
    description: "Path to translation folder"
    required: false
    default: "translations/**/*.po"
  only-languages:
    description: "Only check these languages, comma separated list"
    required: false
    default: ""
  ignore-languages:
    description: "Check all languages expect this one, comma separated list"
    required: false
    default: ""
  token:
    description: "GitHub Secret Token; if not given the check result is not attached to the commit."
    required: false
    default: ""
  min-coverage:
    description: "Minimum percentage (between 0.0 and 100.0) required to mark the check successful."
    required: false
    default: "0.0"
outputs:
  coverage:
    description: "Coverage percentage"
runs:
  using: "node12"
  main: "dist/index.js"